@MONATE.Web.Server_HostAddress = http://localhost:5177

POST {{MONATE.Web.Server_HostAddress}}/VerifyEmail/
Accept: application/json

###

POST {{MONATE.Web.Server_HostAddress}}/VerifyEmail/VerifyCode
Accept: application/json

###