name: Deploy Portfolio Site
run-name: ${{ github.actor }} is deploying portfolio site

on:
  push:
    branches:
     - master

jobs:
  deploying:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: '8.0'
        
      - name: Install dependencies for frontend
        run: |
          npm install
          npm audit fix
        working-directory: ./monate.web.client

      - name: Build frontend
        run: npm run build
        working-directory: ./monate.web.client

      - name: Copy frontend to EC2
        run: |
          scp -i ./monate.pem -r ./dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }}:/var/html
        working-directory: ./monate.web.client
      
      - name: Build backend
        run: |
          dotnet restore
          dotnet build
          dotnet publish -c Release -o ./publish
        working-directory: ./MONATE.Web.Server

      - name: Copy backend to EC2
        run: |
          scp -i ./monate.pem -r ./publish/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }}:/home/publish
        working-directory: ./MONATE.Web.Server

      - name: Restart backend on EC2
        run: |
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo systemctl restart monate-api.service'

      - name: Restart frontend on EC2
        run: |
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo systemctl restart nginx'