name: Deploy Portfolio Site
run-name: ${{ github.actor }} is deploying portfolio site

on:
  push:
    branches:
     - master

jobs:
  deploying:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: '8.0'
        
      - name: Install dependencies for frontend
        run: |
          npm install
          npm audit fix
        working-directory: ./monate.web.client

      - name: Build frontend
        run: npm run build
        working-directory: ./monate.web.client

      - name: Setup SSH key for EC2 access
        run: |
          echo "${{ secrets.EC2_SSH }}" > ./monate.pem
          chmod 600 ./monate.pem

      - name: Add EC2 host key to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_SERVER }} >> ~/.ssh/known_hosts

      - name: Copy frontend to EC2
        run: |
          scp -i ../monate.pem -r ./dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }}:/home/${{ secrets.EC2_USER }}/publish/frontend
        working-directory: ./monate.web.client
      
      - name: Build backend
        run: |
          dotnet restore
          dotnet build
          dotnet publish -c Release -o ./publish
        working-directory: ./MONATE.Web.Server

      - name: Configure dotenv
        run: |
          mkdir -p ./publish
          echo "${{ secrets.DOT_ENV }}" > ./.env
        working-directory: .MONATE.Web.Server/publish

      - name: Copy backend to EC2
        run: |
          scp -i ../monate.pem -r ./publish/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }}:/home/${{ secrets.EC2_USER }}/publish/backend
        working-directory: ./MONATE.Web.Server

      - name: Restart backend on EC2
        run: |
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo systemctl restart monate-api.service'

      - name: Restart frontend on EC2
        run: |
          ssh -i ./monate.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_SERVER }} 'sudo systemctl restart monate-frontend.service'